[package]
name = "target-android"
version = "0.1.0"
authors = ["noxim <aaro.peramaa@gmail.com>"]
edition = "2018"

[package.metadata.android]
package_name = "xyz.noxim.kea"
label = "Kea"
fullscreen = true


[dependencies]
game = { path = "../game" }
kea = { path = "../engine", default-features = false, features = ["backend-vk"] }
kea-dev = { path = "../util/kea-dev" }