[package]
name = "target-desktop"
version = "0.1.0"
authors = ["noxim <aaro.peramaa@gmail.com>"]
edition = "2018"

[dependencies]
game = { path = "../game" }
kea = { path = "../engine" }
kea-dev = { path = "../util/kea-dev" }
gilrs = "0.7"
audio-ears = { path = "../util/audio-ears" }