[package]
name = "kea-cpal"
version = "0.1.0"
authors = ["noxim <aaro.peramaa@gmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 1

[dependencies]
kea = { path = "../../engine" }
cpal = "0.10"
lewton = "0.9"
parking_lot = "0.9"