default-target = "asmjs-unknown-emscripten"

[cargo-web]
minimum-version = "0.6.0"

[target.emscripten]
# prepend-js = "src/emscripten_runtime.js"
link-args = ["-s", "USE_SDL=2", "-s", "DEMANGLE_SUPPORT=1"]
