[package]
name = "game"
version = "0.0.0"
authors = ["noxim <aaro.peramaa@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.20.1"
kea = { path = "../engine" }

[build-dependencies]
kea = { path = "../engine" }