image: "rust:latest"

engine:
  script:
  - rustc --version && cargo --version
  - cd engine
  - cargo build --verbose

desktop:
  before_script:
  - apt-get update
  - apt-get install -y libudev-dev
  script:
  - rustc --version && cargo --version
  - cd target-desktop
  - cargo build --verbose

util-keapack:
  allow_failure: true
  script:
  - cd util/keapack
  - cargo build --verbose

pages:
  stage: deploy
  script:
  - rustc --version && cargo --version
  - cd engine
  - cargo doc
  - rm -rf public
  - mv target/doc/ ../public
  - echo '<meta http-equiv="refresh" content="0; url=kea">' > ../public/index.html
  artifacts:
    paths:
    - public
