image: "rust:latest"

stages: 
- core
- tier1
- tier2
- tier3
- component
- docs

engine:
  stage: core
  script:
  - rustc --version && cargo --version
  - cd engine
  - cargo build --verbose

desktop:
  stage: tier1
  before_script:
  - apt-get update
  - apt-get install -y libudev-dev libasound2-dev
  script:
  - rustc --version && cargo --version
  - cd target-desktop
  - cargo build --verbose

web:
  stage: tier2
  before_script:
  - cargo install --force cargo-web
  script:
  - cd target-web
  - cargo web build --verbose


util-vgpack:
  stage: component
  allow_failure: true
  script:
  - cd util/vgpack
  - cargo build --verbose

util-vg-cpal:
  stage: component
  allow_failure: true
  before_script:
    - apt-get update && apt install -y libudev-dev libasound2-dev
  script:
  - cd util/vg-cpal
  - cargo build --verbose

util-vg-gilrs:
  stage: component
  allow_failure: true
  before_script:
    - apt-get update && apt install -y libudev-dev libasound2-dev
  script:
  - cd util/vg-gilrs
  - cargo build --verbose

util-vg-glium:
  stage: component
  allow_failure: true
  script:
  - cd util/vg-glium
  - cargo build --verbose

util-vg-hal:
  stage: component
  allow_failure: true
  script:
  - cd util/vg-hal
  - cargo build --verbose

util-vg-wgpu:
  stage: component
  allow_failure: true
  script:
  - cd util/vg-wgpu
  - cargo build --verbose

util-vg-sdl2:
  stage: component
  allow_failure: true
  script:
  - cd util/vg-sdl2
  - cargo build --verbose

pages:
  stage: docs
  before_script:
  - rustup toolchain add nightly
  script:
  - rustc --version && cargo --version
  - cd engine
  - cargo +nightly doc
  - rm -rf public
  - mv target/doc/ ../public
  - echo '<meta http-equiv="refresh" content="0; url=vg">' > ../public/index.html
  artifacts:
    paths:
    - public
