image: "rust:latest"

engine:
  before_script:
  - rustup update nightly
  - rustup default nightly
  - apt-get update
  script:
  - rustc --version && cargo --version
  - cd engine
  - cargo build --verbose

desktop:
  before_script:
  - rustup update nightly
  - rustup default nightly
  - apt-get update
  - apt-get install -y libudev-dev
  script:
  - rustc --version && cargo --version
  - cd target-desktop
  - cargo build --verbose

pages:
  before_script:
  - rustup update nightly
  - rustup default nightly
  script:
  - rustc --version && cargo --version
  - cd engine
  - cargo doc
  - rm -rf public
  - mv target/doc/ ../public
  - echo '<meta http-equiv="refresh" content="0; url=kea">' > ../public/index.html
  artifacts:
    paths:
    - public
  only:
  - rewrite
