sudo: true
language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - osx
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build --no-default-features --features=backend-gl
  - cargo build --no-default-features --features="backend-gl backend-mt"
