[package]
name = "vg"
version = "0.0.0"
authors = ["noxim <aaro.peramaa@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
log = "0.4"
emoji-logger = "0.1"
tokio = { version = "0.3", features = ["rt", "net", "time"] }
tokio-tungstenite = "0.12"
futures = "0.3"
# websocket = "0.26"
bytemuck = "1"
ultraviolet = { version = "0.7", features = ["bytemuck", "serde"] }
fxhash = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
winit = { version = "0.23", features = ["serde"] }
wgpu = "0.6"
egui = { version = "0.3", features = ["serde"] }
egui_wgpu_backend = "0.2"
egui_winit_platform = "0.2"
image = "0.23"


[build-dependencies]
anyhow = "1.0"
fs_extra = "1"
glob = "0.3"
shaderc = "0.5"

[profile.dev]
# asset packing is painfully slow without _some_ optimizations, also audio
# stutters like crazy
opt-level = 1