[package]
name = "vg"
version = "0.0.0"
authors = ["noxim <aaro.peramaa@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
log = "0.4"
emoji-logger = "0.1"
tokio = { version = "0.3", features = ["rt", "net", "time", "sync", "rt-multi-thread"] }
# tokio-tungstenite = "0.12"
tungstenite = "0.13"
futures = "0.3"
# websocket = "0.26"
bytemuck = "1"
ultraviolet = { version = "0.7", features = ["serde"] }
glam = { version = "0.12", features = ["serde"] }
fxhash = "0.2"
serde = { version = "1", features = ["derive"] }
# serde_json = "1"
bincode = "1"
winit = { version = "0.23", features = ["serde"] }
# wgpu = "0.6"
# egui = { version = "0.3", features = ["serde"] }
# egui_wgpu_backend = "0.2"
# egui_winit_platform = "0.2"
# image = "0.23"
rend3 = { path = "../rend3/rend3" }
rend3-list = { path = "../rend3/rend3-list" }
lazy_static = "1"
wavefront = "0.1"
png = "0.16"
laminar = "0.4"
# lz4_flex = "0.7"

[profile.dev]
# asset packing is painfully slow without _some_ optimizations, also audio
# stutters like crazy
opt-level = 0
lto = "off"