[package]
name = "kea"
version = "0.1.0"
authors = ["Noxim <noxim#6410>"]
# autobins = false

[lib]
name = "kea"
path = "src/lib.rs"
crate-type = ["staticlib", "lib"]

# crate-type = ["staticlib", "bin"]
# crate-type = ["staticlib"]

[package.metadata.android]
package_name = "xyz.noxim.kea"
label = "Kea DEV"
res = "res"
assets = "assets"
icon = "@mipmap/ic_launcher"

[dependencies]
android_glue = { git = "https://github.com/tomaka/android-rs-glue" }
glutin = "0.18.0"
gl = "0.10.0"
png = "0.12.0"