[package]
name = "vg"
version = "0.0.0"
repository = "https://owo.codes/noxim/vg"
homepage = "https://noxim.xyz/vg"
authors = ["noxim <aaro.peramaa@gmail.com>"]
license = "ISC"
edition = "2018"

[dependencies]
async-trait = "0.1"
