[package]
name = "vg-native"
version = "0.1.0"
authors = ["noxim"]
edition = "2018"

[features]
default = ["wasm"]
wasm = ["rust-wasm"]

[dependencies]
rust-wasm = { path = "../rust-wasm", optional = true }