[dependencies.core]
stage = 0

[dependencies.alloc]
stage = 1

[dependencies.libc]
stage = 2
default-features = false
features = ["align", "rustc-dep-of-std"]

# [dependencies.rand]
# stage = 3
# git = "https://github.com/rust-lang-nursery/rand"
# default-features = false

#[dependencies.libc]
#stage = 3
#default-features=false 
#features = ["align"] 

[dependencies.std]
git = "https://github.com/ischeinkman/libnx-rs-std"
branch = "switch" 
default-features = false
features = [
    "panic-unwind", 
    # "backtrace",
]
stage = 3
