[package]
name = "kea-glium"
version = "0.1.0"
authors = ["noxim <aaro.peramaa@gmail.com>"]
edition = "2018"

[dependencies]
kea = { path = "../../engine" }
glium = "0.22.0"
# glium = { git = "https://github.com/glium/glium/" }