[package]
name = "vg-glium"
version = "0.1.0"
authors = ["noxim <aaro.peramaa@gmail.com>"]
edition = "2018"

[dependencies]
vg = { path = "../../engine" }
glium = "0.25.1"
# glium = { git = "https://github.com/glium/glium/" }