[package]
name = "vg-builder"
version = "0.1.0"
authors = ["Aaro Perämaa <peramaa@soramitsu.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
