[package]
name = "keapack"
version = "0.2.0"
authors = ["noxim <aaro.peramaa@gmail.com>"]
edition = "2018"
description = "A utility for handling asset packs for the Kea game engine"

[dependencies]
kea = { path = "../../engine" }