[package]
name = "vg-cpal"
version = "0.1.0"
authors = ["noxim <aaro.peramaa@gmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 1

[dependencies]
vg = { path = "../../engine" }
cpal = "0.11"
lewton = "0.10"
parking_lot = "0.10"