name: tier1

on: [push]

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        sudo apt update && sudo apt install -y libasound2-dev libudev-dev
        cd target-desktop
        cargo build --verbose
  win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        cd target-desktop
        cargo build --verbose
  mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        brew update && brew install rustup
        rustup-init -y && source $HOME/.cargo/env
        cd target-desktop
        cargo build --verbose
